spring.application.name=youtube
server.port=8080



#        DATABASE
########################
spring.datasource.url=jdbc:postgresql://localhost:5432/youtube_user_db
spring.datasource.username=youtube_user
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


##        EMAIL
#########################
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=bmuxammadov1@mail.ru
spring.mail.password=niOZSLvlteafTvkDxhOq
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000


#########################
# JWT
#########################
jwt.secret.key=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5HZW5lcmF0aW9uMTIzNDU2Nzg5MA==


