spring.application.name=youtube
server.port=8080
app.url=http://localhost:8080


#        DATABASE
########################
spring.datasource.url=jdbc:postgresql://localhost:5432/youtube
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


########################
#        EMAIL
########################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amriddinjavqochdiyev@gmail.com
spring.mail.password=ockgvhdsoqroxayv
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


########################
# JWT
########################
jwt.secret.key=2d4f8a3c7e9b1f6a5d8c2e4f7a9b3c6d
jwt.token.validity=86400000

############# ATTACH
attach.upload.folder=D:/uploads/youtube/
server.url=http://localhost:8080