### 1. Change Password
PUT http://localhost:8080/api/profile/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGlAZ21haWwuY29tIiwiaWQiOjIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzgyNTcxMjI0LCJleHAiOjE3ODI2NTc2MjR9.cjCe_nEBqAG6CWEd90wSxWRqNVr2hvnhZ3-kOGBOIVo

{
  "oldPassword": "123456",
  "newPassword": "changedpas12"
}

###

### 3. Update Profile Detail
PUT http://localhost:8080/api/profile/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGlAZ21haWwuY29tIiwiaWQiOjIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzgyNTcxMjI0LCJleHAiOjE3ODI2NTc2MjR9.cjCe_nEBqAG6CWEd90wSxWRqNVr2hvnhZ3-kOGBOIVo

{
  "name": "ALIJON",
  "surname": "Toshmatov"
}

###

### 5. Get Profile Detail
GET http://localhost:8080/api/profile/detail
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGlAZ21haWwuY29tIiwiaWQiOjIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzgyNTcxMjI0LCJleHAiOjE3ODI2NTc2MjR9.cjCe_nEBqAG6CWEd90wSxWRqNVr2hvnhZ3-kOGBOIVo

###

### 6. Create Profile (ADMIN token kerak)
POST http://localhost:8080/api/profile/admin/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbWlyQGdtYWlsLmNvbSIsImlkIjoxMSwicm9sZXMiOlsiQURNSU4iXSwiaWF0IjoxNzgyNTQ5NjQxLCJleHAiOjE3ODI2MzYwNDF9.hwAP5gk-LtJq9yRY04CEZzeR28ojxrcWL00NJu8-cwM

{
  "name": "Admin1",
  "surname": "admin",
  "email": "admin1@gmail.com",
  "password": "admin1234",
  "role": "ADMIN"
}

###