### 1. Create Report
POST http://localhost:8080/api/report
Content-Type: application/json
Authorization: Bearer USER_TOKEN

{
  "entityId": "CHANNEL_ID",
  "type": "CHANNEL",
  "content": "Bu kanal spam tarqatmoqda"
}

###

### 2. Pagination (ADMIN)
GET http://localhost:8080/api/report/pagination?page=0&size=10
Authorization: Bearer ADMIN_TOKEN

###

### 3. Delete (ADMIN)
DELETE http://localhost:8080/api/report/1
Authorization: Bearer ADMIN_TOKEN

###

### 4. By UserId (ADMIN)
GET http://localhost:8080/api/report/by-user/1?page=0&size=10
Authorization: Bearer ADMIN_TOKEN

###